### ISSUE TITLE
1

### ISSUE THREAD

**Issue by zzh0107** [yong-s/alms#1]
alipays://platformapi/startapp?saId=10000007&qrcode=https%3A%2F%2Fqr.alipay.com%2Ffkx17568wleuqk0ebdb8ia3
收款码连接是什么?

**Comment by yong-s** [comment]
收款码的链接，用二维码工具扫一下识别出来，记得要url encode一下

**Comment by realzsan3** [comment]
> alipays://platformapi/startapp?saId=10000007&qrcode=https%3A%2F%2Fqr.alipay.com%2Ffkx17568wleuqk0ebdb8ia3 收款码连接是什么?

收款码的链接，用二维码工具扫一下识别出来，记得要url encode一下

**Comment by zzh0107** [comment]
我扫出来的不一样,,,,,,能不能出个教程

**Comment by realzsan3** [comment]
> 我扫出来的不一样,,,,,,能不能出个教程

扫出来的应该是这个 `https%3A%2F%2Fqr.alipay.com%2Ffkx17568wleuqk0ebdb8ia3`，放到`qrcode=`后
